import { Link } from 'react-router-dom';
import DataLayout from '@/components/DataLayout';

const sections = [
  ['store', 'What RepForge stores', 'Account details (name, email where provided, hashed password for password accounts), workspace membership, sales profiles and custom scenarios. Simulations include transcripts, AI evaluations, coaching, retries, progress and timestamps. Optional report ratings and pseudonymous usage events are stored separately. Guest practice is also stored in the database—not only in your browser.'],
  ['audio', 'Your microphone and AI voice', 'RepForge receives recognised speech as text, not a recording of your microphone. Your browser’s speech-recognition service may send microphone audio to its own provider; that depends on the browser. ElevenLabs receives the AI prospect text for speech output, which can repeat information you shared. RepForge temporarily caches generated prospect audio for up to one day; this is not a recording of you. Typed practice avoids microphone use, but its text still goes to the AI provider.'],
  ['ai', 'Where your information goes', 'Transcript text, scenario and product context, relevant earlier-call memory, and coaching prompts are sent to the configured AI service: OpenAI, or Anthropic through Emergent’s integration. ElevenLabs supplies generated speech. Emergent hosts the app and manages optional Google sign-in; Google/Emergent supply identity details to connect your account. We do not request access to your Gmail, Drive or Calendar. Provider processing can take place outside your country.'],
  ['providers', 'Provider retention is separate', 'RepForge has not verified zero-retention or provider training opt-outs for these service accounts. Provider retention, safety logging and data-use terms apply independently. Deleting data here does not erase copies already processed by providers, infrastructure logs or private operator backups. We cannot promise a fixed backup purge date or independently verify provider deletion.'],
  ['access', 'Who can see your practice', 'Your history and export require your authenticated session. Verified workspace managers can view team performance and assignments; a matching organisation name does not grant access. Authorised service operators can access the database for maintenance and support. Platform-owner usage reporting uses pseudonymous events without transcript text, names or emails. This is not a promise of end-to-end encryption or a security certification.'],
  ['retention', 'How long data stays', 'Training and profile records remain until you delete them; there is no automatic guest-account expiry. Closing a tab, clearing browser storage or signing out is not server deletion. Temporary Google sign-in flows expire after 10 minutes, replay-protection records after one day, recovery requests after three days and invitations after two days. MongoDB expiry is asynchronous.'],
  ['browser', 'Cookies and browser storage', 'The essential repforge_session cookie maintains sign-in (up to 14 days). A 12-hour bearer fallback is stored in tab sessionStorage for cookie-blocked previews. Browser storage also holds your cached user ID, cross-tab sign-in signal, temporary Google sign-in proof and microphone-check state. RepForge has no implemented advertising-cookie banner, paid subscription checkout or third-party marketing analytics. Server-side product usage events still exist.'],
  ['controls', 'Your choices and limits', 'Export your JSON or permanently delete your account, current guest data or individual sessions using Your data & controls. Session deletion also removes linked retries, feedback and derived memory. Account deletion removes your active-database records, not other workspace members’ records. Keep any exported file private: a downloaded copy stays on your device after account deletion.'],
  ['sensitive', 'Practise with fictional information', 'Do not enter real customer secrets, sensitive personal information, payment details or health records. This is AI sales training, not medical or crisis support. The AI is instructed to pause roleplay for distress and encourage human help where needed, but detection is not guaranteed and nobody monitors practice for emergencies.'],
];

export default function Privacy() {
  return <DataLayout title='Your practice. Your information.' eyebrow='Privacy notice'>
    <p data-testid='privacy-intro' className='mb-10 max-w-2xl text-base leading-relaxed text-muted-foreground'>A plain-language description of the current RepForge build—not a claim of legal compliance or a promise that third-party services keep no data.</p>
    <div className='grid gap-10 md:grid-cols-[180px_1fr]'><aside><Link to='/data' data-testid='privacy-controls-link' className='text-sm font-semibold text-primary'>Open data controls →</Link></aside><div className='space-y-8'>
      {sections.map(([id, title, text]) => <section key={id} data-testid={`privacy-section-${id}`} className='border-b border-border pb-7'><h2 data-testid={`privacy-title-${id}`} className='font-heading text-lg font-bold'>{title}</h2><p data-testid={`privacy-copy-${id}`} className='mt-3 text-sm leading-7 text-muted-foreground'>{text}</p></section>)}
      <section data-testid='privacy-provider-sources'><h2 data-testid='privacy-sources-title' className='font-heading text-lg font-bold'>Provider notices</h2><div className='mt-3 flex flex-wrap gap-5 text-sm text-primary'>
        <a data-testid='privacy-openai-source' href='https://developers.openai.com/api/docs/guides/your-data' target='_blank' rel='noreferrer'>OpenAI API data</a>
        <a data-testid='privacy-anthropic-source' href='https://privacy.claude.com/en/articles/7996866-how-long-do-you-store-my-organization-s-data' target='_blank' rel='noreferrer'>Anthropic retention</a>
        <a data-testid='privacy-elevenlabs-source' href='https://elevenlabs.io/privacy-policy' target='_blank' rel='noreferrer'>ElevenLabs privacy</a>
        <a data-testid='privacy-google-source' href='https://policies.google.com/privacy' target='_blank' rel='noreferrer'>Google privacy</a>
      </div><p data-testid='privacy-contact-limit' className='mt-5 text-xs leading-6 text-muted-foreground'>A dedicated privacy mailbox and legal operator details have not been published in this build. Do not send sensitive data through an unverified contact channel. The app operator must supply these details before a broader production launch.</p></section>
    </div></div>
  </DataLayout>;
}